[tools]
checkov = "latest"
go = "latest"
hadolint = "latest"
helm = "latest"
java = "latest"
kubectl = "latest"
lazydocker = "latest"
lazygit = "latest"
lazyjournal = "latest"
lazyssh = "latest"
node = "latest"
pre-commit = "latest"
python = "latest"
rust = "latest"
systemctl-tui = "latest"
uv = "latest"
yamlfmt = "latest"
