- hosts: localhost

  tasks:
    - name: "Install USER packages from apt"
      become: true
      apt:
        name:
          - git
          - curl
          - zsh
          #- exa
          - bat
          - wget
          - tor
          - ranger
          - htop
          # - fuse # Appimage This bomb crashs ubuntu
          - libfuse2 # Appimage
        state: present

    - name: "Install DEVELOPMENT packages from apt"
      become: true
      apt:
        name:
          - make
          - libssl-dev
          - build-essential
          - ca-certificates
          - zlib1g-dev
          - python3-dev
          #- python2-dev
          - libreadline-dev
          - libsqlite3-dev
          - llvm
          - libncursesw5-dev
          - xz-utils
          - tk-dev
          - libxml2-dev
          - libxmlsec1-dev
          - libffi-dev
          - liblzma-dev
          - lzma
          - libbz2-dev

          # Pillow
          - libtiff5-dev
          - libjpeg8-dev
          - libopenjp2-7-dev
          - zlib1g-dev
          - libfreetype6-dev
          - liblcms2-dev
          - libwebp-dev
          - tcl8.6-dev
          - tk8.6-dev
          - python3-tk
          - libharfbuzz-dev
          - libfribidi-dev
          - libxcb1-dev

          # GRUB
          - grub-efi
          - grub2-common
          - os-prober
        state: present

    - name: "Dowloading Nerd Fonts"
      unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Agave.zip
        dest: ~/.fonts
        remote_src: yes

    - name: "GIT clone dotfiles"
      git:
        repo: https://github.com/jorgepvasconcelos/dotfiles
        dest: ~/dotfiles
        depth: 1
    - name: "Copy ~/dotfiles to ~"
      copy:
        src: ~/create_environment/dotfiles/
        dest: ~/

    - name: "GIT clone ASDF"
      git:
        repo: https://github.com/asdf-vm/asdf.git
        dest: ~/.asdf
        version: v0.18.0
        depth: 1

#    - name: "Set zsh as default shell"
#      shell: "chsh -s /usr/bin/zsh"
