- hosts: localhost

  tasks:
    - name: "Install USER packages from pacman"
      become: true
      pacman:
        name:
          - git
          - curl
          - zsh
          #- exa
          - bat
          - wget
          - tor
          - ranger
          - htop
        state: present

    - name: "Install DEVELOPMENT packages from pacman"
      become: true
      pacman:
        name:
          - make
          - openssl
          - base-devel
          - ca-certificates
          - zlib
          - python
          - readline
          - sqlite
          - llvm
          - ncurses
          - xz
          - tk
          - libxml2
          - xmlsec
          - libffi
          - bzip2

          # Pillow
          - libtiff
          - libjpeg
          - openjpeg2
          - zlib
          - freetype2
          - lcms2
          - libwebp
          - tcl
          - tk
          - harfbuzz
          - fribidi
          - libxcb

          # GRUB
          - grub
          - os-prober
        state: present

    - name: "Dowloading Nerd Fonts"
      unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Agave.zip
        dest: ~/.fonts
        remote_src: yes

    - name: "GIT clone dotfiles"
      git:
        repo: https://github.com/jorgepvasconcelos/dotfiles
        dest: ~/dotfiles
        depth: 1
    - name: "Copy ~/dotfiles to ~"
      copy:
        src: ~/create_environment/dotfiles/
        dest: ~/

    - name: "GIT clone PL10K"
      git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: ~/powerlevel10k
        depth: 1
    - name: "GIT clone zsh-autosuggestions"
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        dest: ~/.zsh/zsh-autosuggestions
        depth: 1
    - name: "GIT clone ASDF"
      git:
        repo: https://github.com/asdf-vm/asdf.git
        dest: ~/.asdf
        version: v0.15.0
        depth: 1

#    - name: "Set zsh as default shell"
#      shell: "chsh -s /usr/bin/zsh"
